# Generated by Django 6.0.3 on 2026-04-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_vendor_is_deleted'),
        ('users', '0003_alter_guestprofile_id_vendoradminprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendoradminprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='hotels.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorstaffprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hotels.vendor'),
        ),
    ]
