# Generated by Django 6.0.3 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
